server:
  port: 8090
spring:
  #数据源
  datasource:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
      username: test_hx
      password: test_hx
      hikari:
        #连接池中允许的最小连接数
        minimum-idle: 10
        #连接池中允许的最大连接数
        maximum-pool-size: 100
        #自动提交
        auto-commit: true
        #连接idle状态的最大时长（毫秒），超时则被释放（retired）
        idle-timeout: 30000
        #连接的生命时长（毫秒），超时而且没被使用则被释放（retired），建议设置比数据库超时时长少30秒
        max-lifetime: 1800000
  #sql
  jpa:
    show-sql: true
    database: oracle
    hibernate:
      ddl-auto: none
  #自定义模板
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: HTML5
    enabled: true
  #redis配置
  redis:
    timeout: 30000
    database: 0
    cluster:
      nodes:
        - 127.0.0.1:6001
        - 127.0.0.1:6002
        - 127.0.0.1:6003
      max-redirects: 3
    lettuce:
      pool:
        #连接池最大连接数
        max-active: 1000
        #连接池最大阻塞等待时间
        max-wait: -1
        #连接池最大空闲连接
        max-idle: 10
        #连接池最小空闲连接
        min-idle: 5
env: test